const TaskList = [
  "Whats your fear now",
  "What was your fear",
  "Display most anoying part of your pertner",
  "Best pert of your pertner you like",
  "Best name for your pertner",
  "Give each other a 5-minute massage... with only one hand.",
  "Whisper your favorite fantasy into each other’s ear.",
  "Play a round of strip poker — or any game where the loser loses clothes!",
  "Use ice cubes and explore each other’s neck, arms, or back.",
  "Give your partner a blindfold and let them guess where you’re kissing them.",
  "Send each other a flirty or spicy voice note — right in front of each other.",
  "Use whipped cream or chocolate syrup and lick it off your partner’s finger.",
  "Act out a romantic movie scene... but make it steamy.",
  "Share your wildest dream — then try to turn it into reality",
  "Let your partner choose your outfit for a 'private fashion show' at home",
  "Do your best impersonation of each other",
  "Have a pillow fight for 1 minute",
  "Make a silly dance video and post it",
  "Say I love you in 10 different languages",
  "Share an embarrassing childhood story",
  "Upload a romantic moment with your partner on your status for 24hr",
  "Try to make the other person cry",
  "Send a text to your partner that says 'I love you'",
  "Pretend to be a pet for the next 5 minutes",
  "Write a love letter to your pertner",
  "Share a naughty story",
  "Tell a naughty time you had",
  "Try to make the other person laugh without speaking",
  "Create a secret handshake",
  "Write a poem about the other person",
  "Draw each other’s faces with your eyes closed",
  "Try a blindfolded taste test challenge",
  "Pick a random song and create a dance routine together",
  "Do 10 push-ups together",
  "Take a funny selfie in a random spot",
  "Share your first crush story",
  "dress like you want your pertner to dress",
  "Do a one-minute fashion show using whatever clothes are around",
  "Pretend you're both on a cooking show and make something with only 3 ingredients",
  "Act like animals for 2 minutes and let the other person guess what you are",
  "first to open any Bible vers and read",
  "Have a staring contest",
  "Do 20 jumping jacks together",
  "Take turns telling each other compliments",
  "transafer money to your pertner",
  "choose an outing and take your pertner there",
  "Recreate a movie scene you both love",
  "Try a tongue twister challenge",
  "Paint each other’s nails (if you want to get messy)",
  "Try to keep a straight face while the other person tells a joke",
  "Share an awkward first date story",
  "Do a cartwheel (if you can!) and cheer for each other",
  "Blindfold each other and guess each other's favorite food",
  "Draw a picture of your dream vacation",
  "Make up a funny new handshake",
  "Have a fashion challenge where you create outfits from each other's wardrobe",
  "I will be making all day meal",
  "I will bath you",
  "Speak in movie quotes for the next 10 minutes",
  "Swap clothes and take a photo",
  "Do your best superhero impersonation",
  "Build a fort together using blankets and pillows",
  "Tell each other your perfect day and try to make it happen",
  "i will be paying the bill of this weekend outing",
  "Make a silly song about your favorite thing together",
  "Try to do each other's morning routine for a day",
  "Recreate a famous meme in real life",
  "Play charades with only animal-related actions",
  "Do a role reversal and act like the other person for 5 minutes",
  "Take turns trying to make the other person say the word pickle without laughing",
  "Pretend you're both movie critics and review the last film you watched",
  "Tell each other a secret and then try to guess what the other person’s secret is",
  "Write a love letter to each other, but include something silly",
  "Try a photo scavenger hunt with a list of things to find",
  "Create a couple's handshake or high five",
  "Share your weirdest dream with each other",
  "Draw a love map with places that are special to you",
  "Share your top 5 favorite songs and explain why",
  "Pretend you're both chefs and try to create a delicious meal using random ingredients",
  "Write each other a love letter sealed with a kiss",
  "Slow dance to your favorite song, even without music.",
  "Take a walk under the stars, holding hands.",
  "Make a scrapbook of your favorite memories together.",
  "Plan a surprise date night for each other.",
  "Share your favorite childhood memory and why it’s special.",
  "Take turns whispering sweet things into each other’s ears for one minute.",
  "Cook a meal together with each other’s favorite foods.",
  "Give each other a heartfelt compliment every hour.",
  "Sit in front of your pertner and talk about your dreams for the future.",
  "Leave sweet notes for each other around the house.",
  "Take a photo of each other in your favorite spot.",
  "Write a song or poem about your love.",
  "Reminisce about the first time you met and the moment you knew you liked each other.",
  "Exchange your favorite romantic book and read it together.",
  "Take a bath together with candles and soft music.",
  "Recreate your first date.",
  "Send each other surprise love texts throughout the day.",
  "Hold each other close and watch the sunrise.",
  "Cuddle while watching a romantic movie.",
  "Plan your dream vacation together and pick the destination.",
  "Make a list of the top 10 things you love about each other.",
  "Look through old photos together and share the stories behind them.",
  "Create a playlist of songs that remind you of each other.",
  "Do a couple’s vision board for your future.",
  "Write down your favorite memories together and read them aloud to each other.",
  "Dance under the moonlight to your favorite slow song.",
  "Surprise each other with a handwritten love note.",
  "Take a long walk and talk about your future together.",
  "Create a couple’s secret handshake.",
  "Whisper something romantic into each other’s ear in the dark.",
  "Make a memory jar and fill it with moments you’ve shared.",
  "Take turns sharing what you love most about each other every day for a week.",
  "Have a candlelit dinner at home with just the two of you.",
  "Exchange a small, meaningful gift that reminds you of the other.",
  "Go stargazing and find constellations to name after each other.",
  "Write down your dreams and share them with each other.",
  "Take turns massaging each other’s shoulders or feet.",
  "Leave a love message on the bathroom mirror for the other to find.",
  "Walk hand in hand through a park or around the neighborhood.",
  "Create a memory box with mementos of your time together.",
  "Take a silly selfie and send it to each other with a romantic caption.",
  "Make a list of things you want to do together in the future.",
  "Hold each other close and let the other person pick the next song for your playlist.",
  "Write down your favorite thing about each other and share it.",
  "Pick a random act of kindness and do it for each other.",
  "Watch the sunset together, and share a moment of silence while holding hands.",
  "Plant a tree or a flower together as a symbol of your love.",
  "Share a quiet moment and simply gaze into each other’s eyes.",
  "Celebrate each other’s accomplishments with a special toast.",
];

export default TaskList;
